# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs: 
    - job: 
      steps:
      - script: |
          echo "Building..."

  - stage: staging 
    jobs:
    - deployment: VmDeploy
      displayName: WebDeploy
      environment:
        name: azure-boards
        resourceType: VirtualMachine
        tags: staging
      strategy:
       runOnce:
        deploy:
          steps:
            - script: sudo mv /var/www/releases/current/siteconfig.conf /etc/nginx/sites-available/siteconfig; sudo ln -sf /etc/nginx/sites-available/siteconfig /etc/nginx/sites-enabled/siteconfig
              displayName: Updating Nginx config
  - stage: production
    jobs:
    - deployment: VmDeploy
      displayName: WebDeploy
      environment:
        name: azure-boards
        resourceType: VirtualMachine
        tags: online
      strategy:
       runOnce:
        deploy:
          steps:
            - script: |
                ip=`az vm list-ip-addresses -g colin-rg -n $(hostname) --query "[].virtualMachine.network.privateIpAddresses[0]" -o tsv`
                az network application-gateway address-pool update -g colin-rg --gateway-name regular-coral-load-balancer -n regular-coral-bep --servers $ip
              displayName: Add load balancer entry
